### ISSUE TITLE
Feature request: Rewrite "Pause during refresh rate change"

### ISSUE THREAD

**Issue by newphreak** [FernetMenta/xbmc#180]
It would be really nice if we could rewrite this function to sync audio/video. Now that we know fully how ActiveAE works, we can pause the video for X.X seconds, and make it perfectly sync. This would/should also remove the need to use 175ms delay in advancedsettings.xml etc.

Also, there is another "bug" in here, if you use Pause during refresh rate currently, it plays a second of the audio before actually pausing. Though, 1 in 50 times or so, it will pause correctly. So there seems to be a race condition here.
https://www.dropbox.com/s/1omppfbm2ziscc2/VID_20131012_151329.mp4

**Comment by FernetMenta** [comment]
done: https://github.com/FernetMenta/xbmc/commit/3203529e4091f00adc1a4c17d49ec4f117ea1d49
