### ISSUE TITLE
Movies start with audio only with some skins

### ISSUE THREAD

**Issue by gdachs** [FernetMenta/xbmc#268]
At least with the skins Aeon Nox 5, Amber, Arctic: Zephir and Transparency the movies start playing with audio. The movie is playing invisible in the background. To see it I have to go back to the main menu and  press escape again.

The skins confluence and titan don't have this problem.

I use this kodi Version:
```
root@ubuntu:~# apt-cache policy kodi
kodi:
  Installiert:           2:16.0~git20150725.1344-f8af961-0vivid
  Installationskandidat: 2:16.0~git20150725.1344-f8af961-0vivid
  Versionstabelle:
 *** 2:16.0~git20150725.1344-f8af961-0vivid 0
        500 http://ppa.launchpad.net/wsnipex/xbmc-fernetmenta-master/ubuntu/ vivid/main amd64 Packages
        100 /var/lib/dpkg/status
```

This is the [debug log](http://paste.ubuntu.com/12023538/) made with skin Amber.

@fritsch told you already about this and asked me to create this issue.

**Comment by fritsch** [comment]
Just for completeness: Same with files != HEVC, too?

**Comment by gdachs** [comment]
[Debug log](http://paste.ubuntu.com/12023768/) with  this [movie](https://dl.dropboxusercontent.com/u/55728161/clannad.mkv)

**Comment by FernetMenta** [comment]
I think this is fixed now in my master branch

**Comment by gdachs** [comment]
Thanks! I will test it when it appears in wsnipex ppa.

**Comment by fritsch** [comment]
@gdachs issue is fixed - so please close :-)
