### ISSUE TITLE
mixer video VDPAU

### ISSUE THREAD

**Issue by joethefox** [FernetMenta/xbmc#286]
I'm noticing an issue with master @ 11-sep-2015.
If I enable the "prefer VDPAU mixer video" the picture becomes too dark:
https://lh3.googleusercontent.com/-XA2mYHZaGbo/VfbEhv45IXI/AAAAAAAABoQ/Cm4xcdP-NRs/s1024-Ic42/2015-09-14-145716_1920x1080_scrot.png

otherwise if I turn off the "prefer VDPAU mixer video" option the picture seems good again:
https://lh3.googleusercontent.com/-Sxd1lBVDq2g/VfbEhxaV5vI/AAAAAAAABoM/C23MOooxmTQ/s1024-Ic42/2015-09-14-144334_1920x1080_scrot.png

With current kodi mainline @ 11-sep-2015 enabling or disabling the "prefer VDPAU mixer video" seems not taking any changes. 
VDPAU mixer on:
https://lh3.googleusercontent.com/-WJj9XotM6Gs/VfbIHo8dwTI/AAAAAAAABok/W8P0yKYmTb8/s1024-Ic42/2015-09-14-150436_1920x1080_scrot.png

VDPAU mixer off:
https://lh3.googleusercontent.com/-jD5ekL5XTZo/VfbIHcvbvMI/AAAAAAAABoo/hTCZv_aHBb4/s1024-Ic42/2015-09-14-150703_1920x1080_scrot.png

**Comment by FernetMenta** [comment]
do you have limited color range enabled?

**Comment by joethefox** [comment]
Nope, sadly if I enable the limited color range the final result is ugly: blacks are greys and whites are light gray. The darkness affects only the video playback, the GUI is OK.

**Comment by FernetMenta** [comment]
@laurimyllari could you have a look at this? seems that RGB rendering does something strange now

**Comment by laurimyllari** [comment]
I'll take a look at the code (I don't have nvidia hw).

My initial guess is that VDPAU mixer outputs full range and that gets expanded again by the output shader.

**Comment by FernetMenta** [comment]
mixer outputs full or limited depending on the setting. it was the first component that was able to output limited range.

**Comment by laurimyllari** [comment]
I would set the mixer to always output limited range so dithering can be used later to avoid banding.

**Comment by FernetMenta** [comment]
good idea. that would also fix this issue, right?

**Comment by laurimyllari** [comment]
If my assumptions are correct, yes.

**Comment by FernetMenta** [comment]
we'd better keep full range in mixer. mixer does also noise reduction, sharpness, etc but only with default colour conversion matrix (full range). If set to limited, it uses a custom matrix and loses those features.

**Comment by FernetMenta** [comment]
@joethefox could you test if it is fixed now?

**Comment by joethefox** [comment]
nope, dark video with mixer VDPAU enabled with e40143c build.

**Comment by FernetMenta** [comment]
please post a debug log

**Comment by laurimyllari** [comment]
I haven't had a chance to look at the code, but my guess is that the output stage needs a switch to disable RGB range conversion if it's handled earlier by the VDPAU mixer.

**Comment by FernetMenta** [comment]
@laurimyllari I changed this already: https://github.com/FernetMenta/xbmc/commit/f7052be281a0d4ca1ab0a57018fc9473557930c0

**Comment by joethefox** [comment]
I did some other test:

Mixer VDPAU [ON] + limit color range 16-235 [ON] -> Picture OK / GUI KO (too bright)
Mixer VDPAU [OFF] + limit color range 16-235 [ON] ->  Picture OK / GUI KO (too bright)
Mixer VDPAU [OFF] + limit color range 16-235 [OFF] ->  Picture KO (too bright) / GUI OK

debug log arriving...

**Comment by FernetMenta** [comment]
another fix: https://github.com/FernetMenta/xbmc/commit/502c67e76124be1f92f084472043377c4ac12509

**Comment by joethefox** [comment]
seems that 502c67e has fixed all the issues :)

**Comment by FernetMenta** [comment]
great, then I close this one.
