### ISSUE TITLE
[VideoPlayer]: VDPAU errors

### ISSUE THREAD

**Issue by MilhouseVH** [FernetMenta/xbmc#296]
When playing certain types of material on a Revo3700 (ION2) with VideoPlayer, there are a number of VDPAU errors and video is initially very heavily pixelatated before clearing up after about 5-10 seconds and then playing normally. Although sometimes Kodi will also hang when starting a video (by "hang" I mean the GUI is frozen and no longer responding).

Debug log when playing a video that eventually clears up: http://sprunge.us/eXdP

Debug log playing several videos - those with VDPAU errors are pixellated, while those without are fine. Eventually the final video hangs Kodi (GUI and playback frozen): http://sprunge.us/KJgO

I'm testing [this build](http://forum.kodi.tv/showthread.php?tid=238393&pid=2108535#pid2108535). Without VideoPlayer, there are no VDPAU errors and video playback is normal.

**Comment by FernetMenta** [comment]
what exactly is "without VideoPlayer"?

**Comment by MilhouseVH** [comment]
Without your master ie. with normal dvdplayer.

**Comment by FernetMenta** [comment]
mainline master? same version of ffmpeg?

**Comment by MilhouseVH** [comment]
Mainline master with OpenELEC master updated to ffmpeg 2.8 - this plays without a problem.

I've had a problem building today due to recent merges, but give me an hour or so and I'll have a couple of updated builds with and without your master that I can use for comparison.

I'll also see how it Ubuntu 15.04/x86_64 with a Radeon R7 GPU behaves with/without your master.

**Comment by MilhouseVH** [comment]
I'm not able to reproduce on Ubuntu 15.04/Radeon R7 with Kodi master + FernetMaster. With or without FernetMenta master, videos play fine on Ubuntu.

However on OpenELEC on a Revo3700 with ION2 I do have a problem, but only when including FernetMenta master.

Build #0920b with FernetMenta master: http://sprunge.us/MHOA - VDPAU errors, pixellation
Build #0920c without FernetMenta master: http://sprunge.us/NOhO - video plays without any problem

Both of the above builds include the following patches on top of Kodi master 9f3e337f72818fd5656bc636dee1035f7eb827e3:

FernetMenta master: https://github.com/xbmc/xbmc/compare/xbmc:5dbca12c4f0355d89af4fb991e564bf39863a35e...FernetMenta:2e693fa2c622305b91c2ae14f9b5582e6610a31a

@fritsch's bumps to mesa 11 and enable EGL: https://github.com/fritsch/OpenELEC.tv/commits/jarvis-egl

@stefansaraev's ffmpeg 2.8 bump:  https://github.com/stefansaraev/OpenELEC.tv/compare/51436b7779c292cd33582d3509d43b1b1f608775...stefansaraev:f000f9712e23f7f0332eb78db9cd2934e2750e50

So not sure if this is an OpenELEC specific issue, an ION2 issue, or maybe I've left something out of the build...

**Comment by MilhouseVH** [comment]
The first error when using FernetMenta master is this `RenderManager` error:

```
14:08:47 T:139707980060672  NOTICE: VideoPlayer: Opening: nfs://192.168.0.3/mnt/share/media/Video/TVShows/The Big Bang Theory/Season 7/The Big Bang Theory S07E01.mkv
14:08:47 T:139707980060672 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:08:47 T:139707980060672   ERROR: RenderManager::CreateRenderer: failed to create renderer
14:08:47 T:139706016720640  NOTICE: Thread VideoPlayer start, auto delete: false
14:08:47 T:139706016720640  NOTICE: Creating InputStream
```
Maybe the subsequent VDPAU errors stem from this first error?

There is no such error when using dvdplayer:
```
14:42:05 T:140171847415808  NOTICE: DVDPlayer: Opening: nfs://192.168.0.3/mnt/share/media/Video/TVShows/The Big Bang Theory/Season 7/The Big Bang Theory S07E01.mkv
14:42:05 T:140171847415808 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:42:05 T:140171847415808   DEBUG: CRenderManager::UpdateDisplayLatency - Latency set to 0 msec
14:42:05 T:140171847415808   DEBUG: LinuxRendererGL: Cleaning up GL resources
14:42:05 T:140171847415808   DEBUG: CLinuxRendererGL::PreInit - precision of luminance 16 is 16
14:42:05 T:140169965442816  NOTICE: Thread DVDPlayer start, auto delete: false
14:42:05 T:140169965442816  NOTICE: Creating InputStream
```

**Comment by FernetMenta** [comment]
you can ignore the first error (renderer). was just a logging error and is already fixed in my master.

**Comment by FernetMenta** [comment]
does this occur with any kind of video sample?

**Comment by MilhouseVH** [comment]
I just tried several different videos, some YouTube videos (all OK) and some samples (2x DTS, and 2 "Birds" samples). The DTS videos gave the VDPAU errors the first time I played them, but were OK the second time. The Birds videos consistently give the VDPAU error.

Debug log for all videos: http://sprunge.us/ChUg

The bird20.mkv sample is now on my [dropbox](https://www.dropbox.com/s/r5jvl83b2ufss2q/bird20.mkv?dl=0) (54MB)

**Comment by FernetMenta** [comment]
what if you turn off refresh rate switching?

**Comment by MilhouseVH** [comment]
> what if you turn off refresh rate switching?

Sorry, which setting is that? These are my video settings:

http://i.imgur.com/PN4eHGY.png

http://i.imgur.com/gy7Ue5x.png

http://i.imgur.com/Ri510Dj.png

**Comment by fritsch** [comment]
Video -> Playback: Adjust Refreshrate to match video: OFF <- for testing, it should be massively broken anyways :-)

**Comment by MilhouseVH** [comment]
> Video -> Playback: Adjust Refreshrate to match video: OFF <- for testing, it should be massively broken anyways :-)

Ah right, I had that option set to `Always`.

With the option changed to `Off` the bird20.mkv and other problem videos now play without any VDPAU errors or pixelation.

Close this issue now, or close when refresh rate switching is fixed? Many thanks both.

**Comment by fritsch** [comment]
Keep it open, please.

**Comment by FernetMenta** [comment]
I tested quite a few samples on ID80 with refresh rate switching. I did not observe any issues running Ubuntu 15.04.

**Comment by fritsch** [comment]
You don't happen to have an ION-2 anymore with legacy drivers, cause nvidia stopped supporting them?

**Comment by FernetMenta** [comment]
There's sits an ID11 somewhere on the shelf with a lot of dust on it. It does not have any hard disk so this would mean a lot of work.

**Comment by fritsch** [comment]
@FernetMenta it was a joke - nothing else :-)

**Comment by MilhouseVH** [comment]
Testing a new OpenELEC build on Revo3700/ION2 with [these commits](https://github.com/xbmc/xbmc/compare/xbmc:382696a54cac9a07e312040f88a5dff6a9eb3697...FernetMenta:408e40a939db607d3744675588a1a6b1ca6a00c0), and setting "Adjust Refreshrate to match video" to `Always` is working very well - no VDPAU errors or pixelation when starting playback (and audio is in perfect sync). Many thanks!

However, when "Adjust Refreshrate to match video" is set to `Off`, audio sync becomes a major issue - let me know if I should open a new issue for audio sync, or if you need more details etc. 

Feel free to close this as you see fit. Thanks again.

**Comment by FernetMenta** [comment]
please elaborate on "major issue"

**Comment by MilhouseVH** [comment]
> please elaborate on "major issue"

You're right, should have been more explicit on that.

What I mean is, the audio becomes increasingly out of sync (audio is delayed) as the video plays whenever "Adjust Refreshrate to match video" is `Off` and "Sync playback to display" is `enabled`.

Adding an audio offset fixes the issue temporarily, but audio continues to drift out of sync making it impossible to compensate for with an offset.

Here's a debug with these specific settings (audio offset is zero): http://sprunge.us/IgYZ

By the end of the log (almost 6 minutes of playback) audio is noticeably and increasingly delayed.

PS. I enabled FFMPEG, Video and Audio debug components but there doesn't seem to be much detail in the log (certainly not compared with a RPi build!) - if you need additional components enabled please let me know.

**Comment by FernetMenta** [comment]
should by fixed now: if "sync playback to display" is enable, passthrough get disabled automatically

**Comment by MilhouseVH** [comment]
Confirmed fixed - many thanks.

Closing this - any other problems I'll open a new issue.

**Comment by MilhouseVH** [comment]
One query - would it be worth adding something to the "Sync playback to display" label or description to the effect that enabling this option will disable passthrough? Perhaps it's obvious (and I realise the default "Sync playback" setting is disabled) but I'm pretty sure some users may become confused when they have both passthrough and "Sync playback" enabled, but don't get bitstreamed audio.
