### ISSUE TITLE
Playback doesn't restart after buffering during playback

### ISSUE THREAD

**Issue by wsnipex** [FernetMenta/xbmc#314]
If kodi starts buffering during playback, it never continues after buffer is full.
Happens on live tv and normal videos.

its easiest to reproduce with live tv over wlan, so this is what I did here: 
http://paste.ubuntu.com/13141960/

**Comment by FernetMenta** [comment]
will look at it when back home from gsoc mentor summit

**Comment by FernetMenta** [comment]
I don't see a stalled stream and buffering in this log. at what time do I need to look?

**Comment by wsnipex** [comment]
IIRC in this particular log it happend directly after switching channel. Line 1864 onwards shows the symptom

**Comment by FernetMenta** [comment]
do you have a chance to post a log whe it happens not directly after channel switch?

**Comment by FernetMenta** [comment]
I can't reproduce this here. I start a channel, then pull the sat cable. Buffering window pops up. After plugging in the sat cable again, playback continues normally.

**Comment by wsnipex** [comment]
new log: http://paste.ubuntu.com/13229558/

it happend 2 times in this log.
1st when I manually diabled wlan for 5 secs
2nd: all by itself after playing the channel for ~1 min

**Comment by FernetMenta** [comment]
at what time in log did you disable wlan?

**Comment by wsnipex** [comment]
should have been around 18:59:48, Line 2400

**Comment by wsnipex** [comment]
btw, the only symptom I see in the logs when this happens is: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer

**Comment by FernetMenta** [comment]
could you please try again and hit some key on the keyboard or remote to have an indicator in the log. better than guessing.

**Comment by FernetMenta** [comment]
at line 2400 you entered fullscreen mode, I doubt that you disabled wlan at the exact same time

**Comment by wsnipex** [comment]
http://paste.ubuntu.com/13230440/
all the keypresses at the end of the file are during the hang

**Comment by FernetMenta** [comment]
please post full debug log. this one has no debugging enabled on start

**Comment by FernetMenta** [comment]
I don't want to bother you but I need all info I can get. As mentioned I can not repro this

**Comment by FernetMenta** [comment]
I think I see what's happening there

**Comment by FernetMenta** [comment]
looks like this expression never gets true: https://github.com/FernetMenta/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp#L552

could you please log cachtime and cachetotal, then trigger an issue

**Comment by wsnipex** [comment]
yep, as usual you guess correctly :)
http://paste.ubuntu.com/13240085/

for reference, this is the logging https://github.com/wsnipex/xbmc/commit/fb418761862e3007d713fe7035203ed94b7df289

**Comment by FernetMenta** [comment]
would be great if you could update the logging and try again.

**Comment by wsnipex** [comment]
all nice about floats, but it is always 0

**Comment by wsnipex** [comment]
QED: http://paste.ubuntu.com/13240460/

**Comment by FernetMenta** [comment]
The question is why this is zero. One of the delays here is negative:
https://github.com/FernetMenta/xbmc/blob/master/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp#L93

could you log m_bufferedSamples and stream->m_bufferedTime in this method? this produces lot of messages but your system should easily cope with this. I always prefix this logs with "----------------". makes it easier to read

**Comment by wsnipex** [comment]
http://paste.ubuntu.com/13240813/

**Comment by FernetMenta** [comment]
thanks. hmm, not what I have expected: then sink delay must be negative. could you please add an additional log here: https://github.com/FernetMenta/xbmc/blob/master/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp#L859
I don't see how this can become negative. Only reason I can think of is that ActiveAESink stops working.

status.GetDelay()

**Comment by wsnipex** [comment]
ok, found something.
see this log: http://paste.ubuntu.com/13240932/ with this patch: http://paste.ubuntu.com/13240948/

here bufferedSamples actually increases again, but there still must be some comparison issue

**Comment by FernetMenta** [comment]
I think I found it: https://github.com/FernetMenta/xbmc/blob/master/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp#L552
I forgot that I set steaming to false on pause. That pauses ActiveAESink. The time correction of sink delay must only be applied to sink delay and not buffered samples/time. Then cachtime will result in 0.4 as expected.

**Comment by wsnipex** [comment]
nice. just to confirm, status.delay never gets negative.

**Comment by FernetMenta** [comment]
could you test this patch please: https://github.com/FernetMenta/xbmc/commit/4bd354cbc175d6485e704243a177b2e714943fb1

**Comment by wsnipex** [comment]
this fixes it :+1: 
thanks a lot

**Comment by wsnipex** [comment]
for completeness. the compiler warning that made me try that unsigned patch above:
CPP     /data/src/xbmc/xbmc/settings/dialogs/GUIDialogAudioDSPSettings.o
Engines/ActiveAE/ActiveAE.cpp: In member function ‘ActiveAE::CSampleBuffer* ActiveAE::CActiveAE::SyncStream(ActiveAE::CActiveAEStream*)’:
Engines/ActiveAE/ActiveAE.cpp:2304:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (framesToDelay > m_encoderFormat.m_frames / 2)
                             ^
Engines/ActiveAE/ActiveAE.cpp:2326:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (framesToSkip > m_encoderFormat.m_frames / 2)

**Comment by FernetMenta** [comment]
thanks a lot!
