### ISSUE TITLE
TrueHD and DTS-HDMA stutter

### ISSUE THREAD

**Issue by MilhouseVH** [FernetMenta/xbmc#340]
With the latest PR8486, passthrough playback of TrueHD and DTS-HDMA tracks results in audible stutter, with the AVR display alternating (flickering) between TrueHD (or DTS-HDMA) and "Unknown".

The following debug log shows the playback of two movies - the first, Blade Runner with TrueHD, the second, Captain America with DTS-HDMA:

http://sprunge.us/jAWJ

(Same video and audio playback settings as shown in https://github.com/FernetMenta/xbmc/issues/339)

**Comment by anaconda** [comment]
I'm getting the same audio dropouts with a DTS stream. Apparently this only happens when "err" (as reported in codec info overlay) is greater than 100 ms or some value near that.
(Phone, sorry for any typo.)

**Comment by FernetMenta** [comment]
please test https://github.com/FernetMenta/xbmc/commit/d33e3b84c1af942ecd0ebc40dd919d1825ce4e78

**Comment by MilhouseVH** [comment]
@FernetMenta: Thanks, this fixes the issue.
