### ISSUE TITLE
AE: Subsequent delay of ~750ms

### ISSUE THREAD

**Issue by garbear** [FernetMenta/xbmc#396]
I've written a sink specifically for the Steam Link Low Latency Audio API ([SLAudio.h](https://github.com/ValveSoftware/steamlink-sdk/blob/master/rootfs/usr/include/SLAudio.h)). My code is: https://github.com/garbear/xbmc-retroplayer/blob/steamlink/xbmc/cores/AudioEngine/Sinks/AESinkSteamLink.cpp

The first GUI sound plays instantly, but all subsequent sounds, both from the GUI and from movies, are delayed by ~750ms.

If I change "Keep Audio Device Alive" from 1 minute to "off", the problem disappears and all audio is played without delay.

@fritsch @FernetMenta

**Comment by fritsch** [comment]
As commented on IRC. The blocking / delay in AddPackets is most likely in wrong order. So delay most likely is off at least the blocking time.

If you want max 200 ms buffer and add 50 ms chunks (periodSize). You need to block in AddPackets until you have at least 50 ms space (see the PA sink for examle).

As the comment indicates that it is okay to call steam's Delay method every 50 ms you can directly use theirs or alternative cache it as shown below:

For the AddPackets:

m_delay = GetSteamDelay();
if delay - TotalCache() < periodSize
sleep(periodSize in seconds)
AddPacket
m_delay += periodSize in seconds;

GetDelay() -> return your cached m_delay

**Comment by FernetMenta** [comment]
> If I change "Keep Audio Device Alive" from 1 minute to "off", the problem disappears and all audio is played without delay.

that's exactly how it is supposed to work. in streaming mode the buffers a full and it may take quite some while for a new audio packet added at the end of the queue to become audible. with this setting off the sink gets drained and paused. this is my preferred mode but sinks like AudioTrack or OSX don't support drain mode. further many AVRs go into standby if the sink is paused.

**Comment by fritsch** [comment]
If there is 750 ms audio "in there" - then we need to see it in GetDelay. I think what happens is that AddPackets does not block in a correct way, e.g. you eat more data than you announce in GetCacheTotal

**Comment by fritsch** [comment]
Seeing the output: http://paste.ubuntu.com/15586846/ I have no idea where this 550 ms additional audio currently is ...

**Comment by garbear** [comment]
well if steam link is losing audio, that's not AE's problem :)
